services:
  eprints:
    image: debian:bookworm
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - eprints:/usr/share/eprints
      - ./shared:/var/shared
    ports:
      - "80:80"
    container_name: eprints
volumes:
  eprints:
  mysql:
  shared: