version: '3.4.4'
services:
  eprintsdb:
    image: mariadb:10.4.8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=pub
      - MYSQL_USER=eprints
      - MYSQL_PASSWORD=test
  eprintshttpd:
    build:
      context: .
      dockerfile: eprintshttpd.dockerfile
      args:
        EPRINTS_HOSTNAME: localhost
    ports:
      - "80:80"
    container_name: eprintshttpd
    volumes:
      - eprints:/usr/share/eprints
      - ./shared:/var/shared
    command: "httpd -k start -DFOREGROUND"
volumes:
  eprints:
  mariadb:
  shared: